# Generated by Django 3.2.5 on 2023-10-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADDfood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Itemname', models.CharField(max_length=30)),
                ('Quantity', models.IntegerField()),
                ('Itemtype', models.CharField(max_length=100, null='true')),
                ('Itemdescription', models.CharField(max_length=30)),
                ('datee', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('Contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=30)),
                ('Website', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('Contact', models.IntegerField()),
            ],
        ),
    ]
