# Generated by Django 3.2.5 on 2023-11-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ngoemployeeregister_ngoregister_addfood_cookingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfood',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('over', 'over')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addfood',
            name='uploaded_image',
            field=models.FileField(default=1, upload_to='add_food/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addfood',
            name='cookingtime',
            field=models.TimeField(),
        ),
    ]
