# Generated by Django 3.2.5 on 2023-11-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20231125_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfood',
            name='datee',
            field=models.DateField(),
        ),
    ]
