# Generated by Django 3.2.5 on 2023-11-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_addfood_datee'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfood',
            name='Name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
