# Generated by Django 3.2.5 on 2023-11-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_addfood_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfood',
            name='Itemname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addfood',
            name='Name',
            field=models.CharField(max_length=300),
        ),
    ]
