# Generated by Django 3.2.5 on 2023-11-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20231127_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfood',
            name='datee',
            field=models.DateTimeField(null=True),
        ),
    ]
