# Generated by Django 3.2.5 on 2023-12-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_addfood_datee'),
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('comp', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='addfood',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accept', 'accept'), ('confirm', 'confirm')], max_length=200),
        ),
    ]
