# Generated by Django 3.2.5 on 2023-12-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20231203_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('comp', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='comp',
            new_name='feed',
        ),
    ]
