# Generated by Django 3.2.5 on 2023-12-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_bookingfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingfood',
            name='ngoName',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
