# Generated by Django 3.2.5 on 2023-12-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_bookingfood_w_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingfood',
            name='workername',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
